name: ✨ Sugestão
description: Ideia de funcionalidade ou melhoria
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Como você imagina a solução?
  - type: checkboxes
    id: help
    attributes:
      label: Contribuição
      options:
        - label: Quero implementar isso
